name: flutter_sample02
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.2
  cupertino_icons: ^1.0.2
  #
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.1.5+1
  font_awesome_flutter: ^8.11.0
  http: ^0.12.2
  pedantic_mono: any
  provider: ^5.0.0
  url_launcher: ^6.0.9

flutter_native_splash:
  image: "images/splash.png"
  color: "E1F8FE"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/background_image.jpg
    - images/icon_qiita.png
